
on:
  push:
    branches: [ "main", "master", "patch-1" ]
  pull_request:
    branches: [ "main", "master", "patch-1" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Install dependencies
        run: |
          npm install
          npm install -g react-native-cli

      - name: Generate Android Folder
        run: |
          if [ ! -d "android" ]; then
            # Инициализируем проект с именем "vn"
            npx react-native init vn --version 0.72.6 --skip-install
            cp -r vn/android .
            rm -rf vn
          fi

      - name: Build Android Release
        run: |
          cd android
          chmod +x gradlew
          # Добавляем флаг --no-daemon для экономии памяти
          ./gradlew assembleRelease --no-daemon --stacktrace
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-unsigned
          # Пробуем найти любой APK, который собрался
          path: |
            android/app/build/outputs/apk/release/*.apk
